### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by michaelspeed** [marcin-stasiak/nest-nuxt-integration#1]
Are there any docs for this?

**Comment by marcin-stasiak** [comment]
What documentation do you need for this simple example?

**Comment by michaelspeed** [comment]
is there a way to pass data directly from the controller?

**Comment by marcin-stasiak** [comment]
Just like in a typical client-server application, use axios.

**Comment by marcin-stasiak** [comment]
I added a usage example with vuex store.
